spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/benefitbridge
    username: benefitbridge_user
    password: benefitbridge_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true